apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator-wide
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: guilhem/etcd-operator
        command:
        - etcd-operator
        - -all-namespaces
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
